hapifhir/hapi-fhir-jpaserver-starter

.travis.yml, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigDstu2.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigDstu3.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigR4.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirTesterConfig.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/JpaRestfulServer.java, src/main/resources/hapi.properties, src/main/webapp/WEB-INF/web.xml, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerDstu2IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerDstu3IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java, src/test/java/ca/uhn/fhir/jpa/starter/RandomServerPortProvider.java
@seanmcilvenna would you ming giving this a revue? I've built on your awesome work with the properties file to get it to the point where switching FHIR versions is just a setting in the file and no other changes required.
=> Improve multiversion support

README.md
added back the IntelliJ RunConfig from JPA-example
=> added back the IntelliJ RunConfig from JPA-example repo

README.md
Adding to MySQL configuration section in README to resolve #21.
=> Updated MySQL configuration instructions regarding integration test issues

src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/resources/hapi.properties
- enforce referential integrity on delete
- enforce referential integrity on write
- auto create reference targets
=> Adding properties

pom.xml
See issue https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/58
=> changed maven depencency of mysql to version 8.0.11

src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
See https://github.com/jamesagnew/hapi-fhir/pull/1666
=> Preparing for email TLS support

README.md, src/main/resources/hapi.properties
- Reformat for sub-headings
- Removed duplicates from properties file
=> Improving the quality of readme documentation

pom.xml
Fixes mvn jetty:run for JDK 11+
=> fixes mvn jetty:run

.travis.yml, pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/ApplicationContext.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/JpaRestfulServer.java, src/main/resources/hapi.properties, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR5IT.java
This branch will not be merged until May but is available for anyone wanting to test the 5.0.0 snapshot builds in advance
=> Start 5.0.0 release branch

.travis.yml, README.md, pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/ApplicationContext.java, src/main/java/ca/uhn/fhir/jpa/starter/EmpiConfig.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/JpaRestfulServer.java, src/main/resources/empi-rules.json, src/main/resources/hapi.properties, src/main/resources/logback.xml, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR5IT.java
Don't merge this until the hapi empi work is merged
=> Changes for empi (as well as subscriptions and partitions)

src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/resources/hapi.properties
Added support for configurable client ID strategy
=> Added support for configurable client ID strategy

README.md, src/main/java/ca/uhn/fhir/jpa/starter/EmpiConfig.java, src/main/resources/empi-rules.json
This closes #116 
* Fix EMPI rules json to match new format 
* Fix EmpiSettings to actually return a bean. 
* Update readme to indicate requirements for enabling EMPI.
=> Fix empi bug

src/main/resources/hapi.properties
Closes #104, corrects CORS property name.
=> Update CORS property name

Dockerfile
Reverts hapifhir/hapi-fhir-jpaserver-starter#155
=> Revert "Docker buid - heap memory error"

src/main/resources/application.yaml
During the change to yaml properties server_address was lost. Re-added.
=> re-added server_address to application.yaml

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/resources/application.yaml
=> Conditionally add the default NarrativeGenerator to the context

pom.xml
=> Use the select2 webjar version from parent pom

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/resources/application.yaml
See https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/186
Tests pass (though I didn't change any), which is to say that I'm fixing things that don't yet have test coverage.
(Normally I'd add them; but it's a time committment I can't cover at the moment)
=> issue 186: minor fixes in partitioning config

src/main/java/ca/uhn/fhir/jpa/starter/EnvironmentHelper.java, src/main/resources/application.yaml
=> Jpa.properties always overridden

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/resources/application.yaml
=> Added configuration option for the ApacheProxyAddressStrategy

src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/resources/application.yaml
Currently CORS didn't work with authorization and origin '*'
This PR changes allowed_origin to allowed_origin_header, which works, as it never returns '\*'
=> FIXING CORS: changed CORS to allowed origin pattern

src/main/resources/application.yaml
Making comments in config consistent. Reorganizing to be a little cleaner. Adding `client_id_strategy`
=> Config cleanup/consitency

README.md
Referencing discussion on google group. 
https://groups.google.com/g/hapi-fhir/c/v1c-i4n6sKk
=> readme suggestion

pom.xml
This fixes https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/237
=> Add snakeyaml to dependencies

pom.xml
Reverts hapifhir/hapi-fhir-jpaserver-starter#248
=> Revert "Adding dependency to snakeyaml"

.gitignore, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
What this commit has achieved:
1. Fixed failing tests in `ExampleServerR4IT` due to:
```
org.awaitility.core.ConditionTimeoutException: Condition with ca.uhn.fhir.jpa.starter.ExampleServerR4IT was not fulfilled within 10 seconds.
```
default await time from Awaitility is 10 seconds
2. Added entries in `.gitignore` related to STS IDE
=> Affected Issue(s): Fix failing test

src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigDstu3.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigR4.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigR5.java, src/main/resources/application.yaml
Related to https://github.com/hapifhir/hapi-fhir/pull/3192
=> Https support for es

src/main/resources/application.yaml
added warning to     advanced_lucene_indexing: false property
=> Add disclaimer for advanced_lucene_indexing

src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java
=> Fix applying supported_resource_types

src/main/resources/application.yaml
`daoconfig_client_id_strategy`does not resolve and is a duplicate of `client_id_strategy`
=> removed wrong and duplicated config entry

Dockerfile, README.md
=> Added OpenTelemetry Java Agent JAR to container image

pom.xml
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/375
=> changes to pom.xml to enable publishing

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/resources/application.yaml
=> Inclusion of bulk data instrumentation

Dockerfile
java17 regular doesn't have ARM, java17-debian11 does
=> Better support for ARM

src/main/java/ca/uhn/fhir/jpa/starter/annotations/OnImplementationGuidesPresent.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigDstu2.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
This PR extracts the installation of IG's to its own bean.
=> Extract IG loading

src/main/resources/application.yaml
this config option was lost during the property -> yaml transition
=> added back lost config entry: allowed_bundle_types

src/main/java/ca/uhn/fhir/jpa/starter/annotations/OnCorsPresent.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java
=> fix: configuration of cors

src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java
=> removed duplicated and wrong subscription code

docker-compose.yml, src/main/resources/application.yaml
Switching to Postgres database as MySQL is deprecated https://hapifhir.io/hapi-fhir/docs/server_jpa/database_support.html
Closes #412
=> Switch to Postgres database

src/main/resources/application.yaml
Addressing https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/444
=> revering to H2

pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/annotations/OnEitherVersion.java, src/main/java/ca/uhn/fhir/jpa/starter/annotations/OnR4BCondition.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigR4B.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/java/ca/uhn/fhir/jpa/starter/common/validation/RepositoryValidationInterceptorFactoryR4B.java, src/main/resources/application.yaml, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4BIT.java
See also https://github.com/hapifhir/hapi-fhir/issues/4276
=> fixes for support of R4B / 6.2.0

charts/hapi-fhir-jpaserver/Chart.lock, charts/hapi-fhir-jpaserver/Chart.yaml, charts/hapi-fhir-jpaserver/README.md, charts/hapi-fhir-jpaserver/templates/deployment.yaml, charts/hapi-fhir-jpaserver/templates/tests/test-endpoints.yaml, charts/hapi-fhir-jpaserver/values.yaml
Updates the chart to use the latest image.
Also updates all other dependencies and image tags.
=> Updated Helm chart to use image 6.2.1 and latest PostgreSQL

.github/workflows/maven.yml
Closes [484](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/484)
=> Update pipeline to run integration tests.

src/main/resources/application.yaml
Fix spelling error in comments section
=> Spelling error in Application.yaml

src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java
=> 497 - Fix typo on property setter

charts/hapi-fhir-jpaserver/Chart.yaml, charts/hapi-fhir-jpaserver/README.md, charts/hapi-fhir-jpaserver/README.md.gotmpl, charts/hapi-fhir-jpaserver/ci/extra-config-values.yaml, charts/hapi-fhir-jpaserver/templates/application-config.yaml, charts/hapi-fhir-jpaserver/templates/deployment.yaml, charts/hapi-fhir-jpaserver/templates/tests/test-endpoints.yaml, charts/hapi-fhir-jpaserver/values.yaml
Closes #547, closes #548, closes  #549.
=> Updated helm chart with additional config settings

pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/java/ca/uhn/fhir/jpa/starter/cr/StarterCrDstu3Config.java, src/main/java/ca/uhn/fhir/jpa/starter/cr/StarterCrR4Config.java, src/test/java/ca/uhn/fhir/jpa/starter/ElasticsearchLastNR4IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
Increments HAPI parent to 6.8.0.
=> Bump to HAPI 6.8.0

README.md
There are some English typos in the README.md file
=> Fixing some typos in README.md

pom.xml
=> Fix #580 Build artifact contain certain unused (but declared) dependencies

Dockerfile, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java
Fix for https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/591
=> Fixing null beans

src/main/java/ca/uhn/fhir/jpa/starter/common/FhirTesterConfig.java
Fixes https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/639
=> fix: reintroduced configurable condition on tester

README.md, pom.xml, src/main/resources/application.yaml
=> 671 - Updated the run instructions.

Dockerfile, README.md, charts/hapi-fhir-jpaserver/Chart.yaml, charts/hapi-fhir-jpaserver/README.md, charts/hapi-fhir-jpaserver/values.yaml, docker-compose.yml, pom.xml, src/main/resources/application.yaml
Updated Parent version to FHIR 7.2.1, fixed Java version for the release, fixed issues when running in Container
=> Updated parent to FHIR 7.2.1

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/resources/application.yaml, src/test/java/ca/uhn/fhir/jpa/starter/ParallelUpdatesVersionConflictTest.java
Add a property to enable the UserRequestRetryVersionConflictsInterceptor interceptor: 
https://hapifhir.io/hapi-fhir/docs/server_jpa/configuration.html#retry-on-version-conflict
=> add property to turn on userRequestRetryVersionConflictsInterceptor

src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
Diff provider was not registered by default. Added it and a test. See #788
=> registered  diff provider

.github/workflows/spotless-check.yml
Uses a proxy for running spotless checks.
=> Use proxy for spotless check

.github/workflows/smoke-tests.yml
This pull request enhances the smoke test workflow in `.github/workflows/smoke-tests.yml` by improving server logging, error detection, and artifact management. The changes aim to make debugging easier and provide better insights into server behavior during tests.
* **Improved server logging**: Added a step to redirect server logs to a file (`logs/server.log`) during the server startup process. This ensures logs are saved for later analysis.
* **Error detection and highlighting**: Introduced a step to scan the server logs for errors, exceptions, or warnings. Any issues found are highlighted in the GitHub Actions log using the `::error::` annotation.
* **Log management**:
- Added a step to display the last 200 lines of the server log in the workflow output for quick review.
- Included a …
=> feat: enhance smoke tests with logging and error highlighting

pom.xml
This pull request includes a small update to the `pom.xml` file, incrementing the `hapi.fhir.jpa.server.starter.revision` property from `1` to `2`.
=> Update revision number

src/main/java/ca/uhn/fhir/jpa/starter/cr/CrCommonConfig.java, src/main/java/ca/uhn/fhir/jpa/starter/cr/CrProperties.java, src/main/resources/application.yaml, src/main/resources/cds.application.yaml
Make TerminologyServerClientSettings configurable for use in clinical-reasoning
=> Add TerminologySeverClientSettings to CR Properties & Config

README.md
Added a one-liner command for installing an Implementation Guide into HAPI.
=> Add quick install command for Implementation Guide
