src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfig.java, src/main/java/ca/uhn/fhir/jpa/demo/HapiProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java
Allow optional, external configurations to override the entries in hapi.properties.
Such configurations can be specified in a properties file outside of the war (or
webapps/hapi-fhir-jpaserver) and the server may be instructed to load the configuration using
-Dhapi.properties=<path-of-external-configuration-file>
This is helpful in at least two use cases:
1. Deploying multiple instances with different configurations (e.g., different databases)
2. Future upgrade - just update the war without the need to change hapi.properties after update.
=> Support for optional, external configuration file

src/main/resources/hapi.properties
Fix for #8. Fixing server_address and server.base so that the URLs will work out of the box with Jetty.
=> Default url

src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java, src/main/resources/hapi.properties
Adds cache timeout configuration property.
This is useful when using hapi-fhir-jpaserver-starter as a test FHIR server which relies on returned results not being stale.
I disabled caching by default.
Thanks!
=> Add cache timeout configuration property. Disabled by default

README.md
Updated readme file with instructions on how to run the hapi server on a different port using Maven
=> Updated readme file with option to change port

Dockerfile, Dockerfile.base, docker-build.bat
These are the Dockerfiles that I used for the documentation here: https://hub.docker.com/repository/docker/hapiproject/hapi
They're also the same Dockerfiles I'm using in my own environment to build and deploy HAPI. They're pretty flexible files, and perform the compile directly in docker, rather than requiring the user to compile the application first and then build the docker image. The advantage to this, is that the docker image is an exact representation of stuff on github, rather than potentially having custom from the machine running the docker build.
=> Updating Dockerfile to build the app from the ground up

src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java
I am happy with most of the hapi properties :-). There is today possibility to override hapi properties by   `-Dhapi.properties` in `JAVA_OPTS` environment variable.
However it is very convenient to just override some of the properties in your container using kubernetes manifest file for your deployment. Like in this example, where I override default DB used by HAPI and set desired version.
```
env: 
- name: HAPI_DATABASE_NAME
value: HAPI_R4
- name: datasource.url
value: "jdbc:sqlserver://mssql-database;databaseName=$(HAPI_DATABASE_NAME)"
- name: datasource.driver
value: com.microsoft.sqlserver.jdbc.SQLServerDriver
- name: hibernate.dialect
value: org.hibernate.dialect.SQLServer2012Dialect
- name: server_address
value: {{http-scheme}}://{{base-url}}{{hapi-r4-base-uri}}
- name: …
```
=> Adding environment variables to override hapi properties file settings

README.md, src/main/resources/application.yaml
This PR will remove the need to run  -Dspring.batch.job.enabled=false and similar when running the hapi fhir jpa server before a few days ago.
Benefits:  Avoid changing build process, and adding command line built parameters when it's not needed
Changes, defaulted the spring batch job enabled to false in application.yaml
=> Spring batch job enabled

src/main/resources/application.yaml
It seems via the adding and removing of the previous PR landed up having 2x the tags for Batch job enabled.
Once on line 2, Once on Line 29
=> Remove Duplicate batch job enabled

Dockerfile
When building in Docker, we sometimes face a heap memory running out when compiling the WAR file.
Setting the MAVEN_OPTS="-Xmx1024m" resolves this
=> Docker buid - heap memory error

pom.xml
The webjar versions are specified in the parent POM. They should not be explicitly mentioned in our POM.
=> Remove webjars versions specified in parent pom

.github/workflows/build-images.yaml, Dockerfile, README.md
This adds a GitHub Actions Workflow to automatically build images from the Dockerfile and push them to both the GHCR.io and the Docker Hub registries.
For this to work, the following repository secrets will need to be created:
- `DOCKERHUB_TOKEN`: the hub.docker.com PAT for the `hapiproject` organization
- `DOCKERHUB_USERNAME`: the username associated with the PAT above
- `GHCR_TOKEN`: a GitHub PAT used to push the image to GHCR.io (GHCR support may need to be enabled for the organization first, see https://docs.github.com/en/packages/guides/enabling-improved-container-support)
Note that the use of GHCR.io is just a suggestion to provide additional registry due to docker.io's recent rate limiting. quay.io would also be a viable choice.
The images are built on each PR, but only pushed if a …
=> Added GitHub actions to build container images

README.md
Just suggested an addition (accepted) to the readme with the wrong property name. Fixed now.
=> fixed property naming in readme

src/main/resources/application.yaml
There was a small indentation error in the application.yaml causing the application startup to fail
We could introduce additional tooling as part of the GitHub Workflows to lint yaml and detect these potential problems earlier (eg https://github.com/github/super-linter).
=> Fixed indentation error in application.yaml

README.md
According to the default application.yaml, it's `hapi.fhir.subscription.resthook_enabled` (with the underscore). I've tested this with the latest docker container and it works. Setting `hapi.fhir.subscription.resthook.enabled=true` does not enable subscriptions. I spent a lot of time breaking my head over this simple variable name. Hopefully, this will help someone.
=> Corrected subscription environment variables

pom.xml
Please consider adding a classes jar artifact, as illustrated here.
The classes jar can be a useful dependency for a project that implements a hapi-fhir server with no test overlay.  It also enables clean separation between code maintained here and specialized code that isn't tightly bound to this project (e.g. custom AuthorizationInterceptor, custom Dockerfile, etc.).
=> add <attachClasses>true</attachClasses> to  maven-war-plugin configuration

pom.xml
At least a few people (myself included) have had problems launching `hapi-fhir-jpaserver-starter` without having snakeyaml added as an explicit dependency.
I'd like merge this change to add it as a dependency. After it is merged, I'd like to delete the tag for 5.4.0 and re-tag it on the HEAD of `master` (including this change) as 5.4.0.
This will cause the docker image to rebuild for 5.4.0, and should solve the problem for at least a few people, if not more.
Please let me know if you're ok with me deleting the 5.4.0 tag and re-creating it on the HEAD of master when you approve/reject this merge request.
=> Adding dependency to snakeyaml

README.md, docker-compose.yml
Mysql docker setup - forcing mysql identifiers (database, table, triggers) naming to lowercase and name comparison to caseinsensitive, so hibernate queries can work even when referencing upper cased table names
=> mysql docker setup patch

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/resources/application.yaml, src/test/resources/application-integrationtest.yaml
Straightforwardly adds the option to leverage the existing delete-expunge capability in HAPI FHIR in the starter server.
You can test this easily:
```
sh build-docker-image.sh
```
Note the hash for your build.
```
docker run -p 8080:8080 \
-e hapi.fhir.expunge_enabled=true \
-e hapi.fhir.delete_expunge_enabled=true \
-e hapi.fhir.allow_multiple_delete=true \
YOUR_BUILD_HASH_HERE
```
Then:
```
curl -H "Content-Type: application/fhir+json" -X DELETE http://localhost:8080/fhir/Patient/?_expunge=true
```
=> Adds ability to use delete-expunge operations to the JPA Starter Server.

.github/workflows/build-images.yaml
per discussion in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/268, this disables pushing the image to the GitHub container registry until permissions are sorted out.
=> only push build images to DockerHub

.github/workflows/build-images.yaml, Dockerfile, pom.xml
1. Bumped HAPI FHIR to 5.5.1
2. Bumped all Dockerfile base images to latest (and Debian 11)
3. Refactored CI to
1. use newer versions of the docker/metadata-action
2. build ARM-compatible variants of the images (Closes #276). This makes the CI significantly slower. If desired, we could disable it for PRs and only build ARM variants on releases.
3. also build and push images tagged with the commit SHA. e.g. this will tag images on pushes to master as `sha-5a0e725` and `sha-5a0e725-distroless`. This makes it easer to test fixes/commits sooner
4. as before, any tag called `image/v1.2.3` will create images tagged as `v1.2.3` and `v1.2.3-distroless`. See https://github.com/chgl/hapi-fhir-jpaserver-starter/pkgs/container/hapi for an example of tags created while I debugged the workflow.
=> Updated to HAPI FHIR 5.5.1 and updated workflows to build ARM-compatible images

README.md, pom.xml
Replacing PR #343. 
MS SQL Server drivers are now publicly available in Maven Central and open-sourced under MIT license.
see: https://github.com/microsoft/mssql-jdbc
If there were not other reasons for excluding it, request to add the dependency to make it easier to use directly with SQL Server without needing to manually add the driver jar files to deployments.
Also added a note to the readme to save people some headaches when using MS SQL Server.
=> add support for ms sql server

pom.xml
This updates the included HAPI FHIR version to 5.7.2.
Thanks to https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/337, A new version of this starter image will allow me to update the liveness and readiness probes used by the Helm Chart deployment to use the out-of-the-box Spring Boot Kubernetes probes (https://docs.spring.io/spring-boot/docs/2.6.6/reference/htmlsingle/#actuator.endpoints.kubernetes-probes.external-state)
=> Updated to HAPI FHIR version 5.7.2

src/main/resources/application.yaml
Lucene indexing was accidentally activated. This reverts the error.
=> Revert accidental default activation of experimental lucene indexing

README.md
To fix the problem raised in [this](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/318) issue.
=> Added instructions about removing Hibernate dialect

pom.xml, src/main/resources/application.yaml
This enables the Prometheus actuator endpoint to expose application metrics on `/actuator/prometheus` (https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.prometheus).
This endpoint is read-only and included by default. I don't believe any critical information is exposed via this endpoint, but we could also run the actuator on different port (via the `management.server.port` property) so it can be firewalled off if desired, combined with `management.endpoint.health.probes.add-additional-paths=true`, health probes can still run on the main server port (see also https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes).
=> Expose Prometheus metrics

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/resources/application.yaml
add option in application.yaml for enable of-type modifier (identifier:of-type)
=> Add: of-type modifier option in application.yaml

pom.xml
Previous HAPI dependency was a SNAPSHOT, this bumps to non-SNAPSHOT version of HAPI (6.0.1).
=> bumping to non-snapshot version

pom.xml
This issue is already fixed upstream. Can be removed with next hapi version upgrade.
https://github.com/hapifhir/hapi-fhir/pull/3676
=> Applying fix from upstream for h2 Binaries

Dockerfile, README.md, pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java, src/main/java/ca/uhn/fhir/jpa/starter/EnvironmentHelper.java, src/main/java/ca/uhn/fhir/jpa/starter/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/StarterJpaConfig.java, src/main/resources/application.yaml
Some of the changes are based on https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/408
To test the changes, I built and pushed the container image as `ghcr.io/chgl/hapi-fhir-jpaserver-starter:6.1.0`, POSTed some resources and read them back. Repeated the test inside the Helm chart with a PostgreSQL database.
Looking forward to a new subsequent container image release to be able to update the Helm chart with a version of the image that contains the OTEL agent!
=> Updated to hapi 6.1.0

src/main/java/ca/uhn/fhir/jpa/starter/util/JpaHibernatePropertiesProvider.java
Currently sonar mark connection.getConnection() as resource leak, since the connection is never closed after dialect has been resolved.  Simply use try-with-resources to ensure connection is closed after usage.
=> Proper close DB connection after dialect was resolved

src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java
SubscriptionDebugLogInterceptor() is only registered if `daoConfig.getSupportedSubscriptionTypes().size() > 0`
fixes: #441
=> fixed SubscriptionDebugLogInterceptor adding logic

README.md, src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/resources/application.yaml, src/test/java/ca/uhn/fhir/jpa/starter/CustomBeanTest.java, src/test/java/ca/uhn/fhir/jpa/starter/CustomInterceptorTest.java, src/test/java/some/custom/pkg1/CustomBean.java, src/test/java/some/custom/pkg1/CustomInterceptorBean.java, src/test/java/some/custom/pkg1/CustomInterceptorPojo.java
The purpose of this PR is to allow users to add interceptors without needing to update the existing configuration classes in HAPI - to make it easier to maintain custom branches without code-clashes in the base project. 
It adds two properties:
hapi.fhir.custom-bean-packages - any packages listed here will be ComponentScan'ed by Spring
hapi.fhir.custom-interceptor-classes - classes here will be discovered by the config (from the application context or via reflection) and registered as interceptors with the server. 
This paradigm could likely be extended for custom providers and possibly other things. 
see also : https://chat.fhir.org/#narrow/stream/179167-hapi/topic/best.20practice.20for.20embedding.20business.20logic
=> allow interceptors to be registered via properties

src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4BIT.java
Closes [478](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/478)
=> Restore rolled back changes to ExampleServerR4BIT that pass unnecessa…ry properties that will cause problems when using hapi-fhir 6.3.6-SNAPSHOT.

pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/Application.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigDstu2.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/test/java/ca/uhn/fhir/jpa/starter/CustomBeanTest.java, src/test/java/ca/uhn/fhir/jpa/starter/CustomInterceptorTest.java, src/test/java/ca/uhn/fhir/jpa/starter/ElasticsearchLastNR4IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerDstu2IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerDstu3IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4BIT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR5IT.java, src/test/java/ca/uhn/fhir/jpa/starter/JpaStarterWebsocketDispatcherConfig.java, src/test/java/ca/uhn/fhir/jpa/starter/MultitenantServerR4IT.java
- Spawned from the crude and messy but effective solution in [480](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/480)
- Remove static code blocks to Application.java and all tests:
- Downgrade logback.core to 1.2.11
- Downgrade logback.classic to 1.2.11
- Downgrade slf4j-api to 1.7.25 >>>>> This is the key difference missing from the first attempt that disabled logging.
- Add a new test config:  JpaStarterWebsocketDispatcherConfig, and add it to @SpringBootTest for all of the ITs:   This solves the NPE on jetty websocket tests that was introduced by the above changes. >>>> Jetty10RequestUpgradeStrategy.upgrade(Jetty10RequestUpgradeStrategy.java:124). >>> Cannot invoke "Object.getClass()" because "obj" is null
=> Upgrade to hapi-fhir 6.3.6-SNAPSHOT:  Alternative solution.

README.md
Updates `README.md` file to inform that MySQL has been deprecated from HAPI FHIR JPA Server
From MR: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/444
=> docs: Updated README.md. Discontinue mysql

pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/Application.java, src/test/smoketest/http-client.env.json
Bumps HAPI to 6.4.0 and fixes a resultant Application configuration issue.
Fixes this error anywhere ca.uhn.fhir.jpa.starter.Application was instantiated:
```log
Parameter 0 of method templateEngine in ca.uhn.fhir.to.FhirTesterMvcConfig required a single bean, but 2 were found:
- templateResolver: defined by method 'templateResolver' in class path resource [ca/uhn/fhir/to/FhirTesterMvcConfig.class]
- defaultTemplateResolver: defined by method 'defaultTemplateResolver' in class path resource [org/springframework/boot/autoconfigure/thymeleaf/ThymeleafAutoConfiguration$DefaultTemplateResolverConfiguration.class]
```
=> Bump HAPI to 6.4.0

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/resources/application.yaml
update to add config option to skip re-loading/re-indexing IG resources that already exist. (defaults to skip)
see:  https://github.com/hapifhir/hapi-fhir/pull/3989
=> configuration option to not reload IG resources that are already loaded

README.md
When running from Docker Hub, it is not convenient to have to copy the full ``application.yaml`` as a starting point. Based on [Spring's property initialization order](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files), it's possible to mount a small version of ``application.yaml`` in the ``config`` folder in the run directory.
=> Update docker-compose sample with small application.yaml

pom.xml
Removed explicit inclusion of snakeyaml due to numerous dependabot security warnings and allow spring-boot-start-actuator to pull it in as a needed dependency.
=> Remove explicit inclusion of snakeyaml

Dockerfile, README.md
Now it is possible to mount a folder with extra classes that are loaded by HAPI. This makes it easy to load an interceptor JAR while using the standard Docker image. The README explains how to use it.
Spring by default uses the WarLauncher. Now the ENTRYPOINT uses the PropertiesLauncher, configured in such a way that it is compatible with the WarLauncher, but adding the folder /app/extra-classes to the loader.path.
=> Simplify using an interceptor with Docker

Dockerfile, README.md, pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/resources/application.yaml
Refactor to use the renamed DaoConfig and ModelConfig classes.
This includes latest commits to master, and passes smoke tests.
=> Use JpaStorageSettings and StorageSettings

pom.xml, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigR4B.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigR5.java, src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR5IT.java
This fixes the following in order to get all tests running (smoke tests included)
* Configs related to Subscription/SubscriptionTopic
* Config for emailSender (see: https://github.com/hapifhir/hapi-fhir/pull/4790)
=> Update to hapi-fhir 6.5.20-SNAPSHOT

.github/workflows/smoke-tests.yml
For smoke test pipeline:
Uses a docker pull to get the IntelliJ HTTP client instead of a direct url.
=> Use docker for HTTP client

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/resources/application.yaml
This PR made the "reload_existing_implementationGuides" property no longer needed or picked up: 
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/577
The property is now part of the PackageInstallerSpec. Removing it for cleanup and to avoid confusion.
=> remove redundant/unused reload-existing-ig property

src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/java/ca/uhn/fhir/jpa/starter/mdm/MdmConfig.java, src/test/java/ca/uhn/fhir/jpa/starter/MdmTest.java
This will close #611 if merged.
What this commit has achieved:
1. MDM requires an implementation of `INicknameSvc`, it was instantiated in `NicknameServiceConfig`
The error message regarding this was:
```
APPLICATION FAILED TO START
Description:
Parameter 2 of method matcherFactory in ca.uhn.fhir.jpa.mdm.config.MdmCommonConfig required a bean of type 'ca.uhn.fhir.jpa.nickname.INicknameSvc' that could not be found.
Action:
Consider defining a bean of type 'ca.uhn.fhir.jpa.nickname.INicknameSvc' in your configuration.
```
2. MDM requires the subscription of type message
The error message regarding this was:
```
2023-12-01 11:34:03 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mdmSubmitterInterceptorLoader': Invocation of init method failed; nested …
```
=> Affected Issue(s): #611

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/mdm/MdmConfig.java, src/main/resources/application.yaml
This correlates to #606
What this commit has achieved:
1. Externalized location of "mdm-rules.json" in the `AppProperties`
2. More info about the `ResourceLoader` interface is available at [here](https://docs.spring.io/spring-framework/reference/core/resources.html#resources-resourceloader)
- Set `hapi.fhir.mdm_rules_json_location` to `file:///D:/SourceCodes/SID/it-team/local-development-resources/federated-fhir-servers-prototype/district-a/mdm-rules.json`
=> Affected Issue(s): #606

.github/workflows/smoke-tests.yml
The smoke tests appear to be failing due to an inability to start the server.
This explicitly sets the profile before running.
=> Explicit profile for smoke test invocation

README.md, src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/StarterJpaConfig.java, src/main/resources/application.yaml, src/test/java/ca/uhn/fhir/jpa/starter/CustomOperationTest.java, src/test/java/some/custom/pkg1/CustomOperationBean.java, src/test/java/some/custom/pkg1/CustomOperationPojo.java
This change allows for a custom operation/provider to be added to the fhir server in the same way a custom interceptor is added.
=> Allow custom operations/providers in addition to interceptors

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml
Per #649 this PR aims to add a new config property to the JPA Server Starter for `server_id_strategy` with some defaulting logic based on what is set for `client_id_strategy`, while at the same time opens up `client_id_strategy` to all possible values (and not just default a.k.a. `ALPHANUMERIC` vs `ANY` which were really the only two options before).
For example, now you can set `client_id_strategy` to `NOT_ALLOWED` which was not possible before (or more to say, sure, you could have set the property to this value, but it would not have actually set the JpaStorageSetting property to anything).
The new `server_id_strategy` is set to null by default and then will be changed to `UUID` if `client_id_strategy` was set to `ANY` (exactly as it was before) provided that `server_id_strategy` has …
=> Allow all client_id_strategy options and add server_id_strategy

src/main/java/ca/uhn/fhir/jpa/starter/ig/ImplementationGuideR5OperationProvider.java
When using R5 and enabling ig_runtime_upload_enabled, the application won't start.
We need to change the package of the Parameters resource used in ImplementationGuideR5OperationProvider.uninstall (probably a copy&paste with too much information carried over).
=> fhir version of Parameters for IG uninstall when using R5

Dockerfile
The directory created for lucene requires escalated privileges to be created. 
This uses ROOT for directory creation, but switches ownership back to 1001 after creation.
Fixes #719
=> Docker + Tomcat: lucene directory creation.

.github/workflows/build-images.yaml, Dockerfile, docker-compose.yml, pom.xml
- Upgrade of Docker Base image for Maven to 3.9.9
- Upgrade OpenTelemetry dependency
=> Updated Dockerfile and pom.xml

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml
Related to discussion here: https://github.com/hapifhir/hapi-fhir/issues/6109 
- expose prefetch threshold setting
- add docs
@bashir2
=> Expose Setting for prefetch thresholds

src/test/java/ca/uhn/fhir/jpa/starter/CdsHooksServletIT.java
I was getting an error running the CdsHooksServletIT.testCdsHooks() test on Windows. The test is blocking while it waits for the CDS Services to be "ready" by looking at the response from _/cds-services_.  I was seeing an empty response from it initially like: 
```
{
"services": []
}
```
This empty response is 22 characters (on Windows), which is the minimum size that hasCdsServices() was looking for. So the test was continuing to run thinking the CDS services were "ready", but they were not. 
This led to: 
```
2024-10-29T12:58:34.199-05:00  INFO 19928 --- [           main] c.u.h.f.c.svc.CdsServiceRegistryImpl     : Unregistered active service opioidcds-10-order-sign
2024-10-29T12:58:34.436-05:00  INFO 19928 --- [o-auto-1-exec-2] fhirtest.access                          : Path[/fhir] …
```
=> fix intermittent error with CDS test

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml, src/main/resources/cds.application.yaml, src/test/resources/application.yaml
Added setting to application.yaml for `conditional_create_duplicate_identifiers_enabled` which was added in hapi-fhir 7.4.0 by https://github.com/hapifhir/hapi-fhir/pull/5983
closes #754
=> add application.yaml setting for conditional_create_duplicate_identifiers_enabled

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml, src/main/resources/cds.application.yaml, src/test/resources/application.yaml
This PR adds the validate_resource_status_for_package_upload configuration parameter to enable override of the default behaviour of filtering resources during package installation based on their status.
Without this configuration, it is not possible to upload StructureDefinition resources with a [status](https://www.hl7.org/fhir/structuredefinition-definitions.html#StructureDefinition.status) of 'draft'.
This feature is required so that resources with a 'draft' state can be installed on a FHIR server for implementation testing prior to publication as 'active'.
=> Config property for validate resource status

src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
Use URI constructor instead of string concatenation, to avoid having static code analysis tool (e.g., Sonarqube) complain about security issue for "Concatenating user-controlled input into a URL".
=> use URI constructor instead of string concatenation

.github/ct/config.yaml, .github/workflows/chart-test.yaml, charts/hapi-fhir-jpaserver/Chart.lock, charts/hapi-fhir-jpaserver/Chart.yaml, charts/hapi-fhir-jpaserver/README.md, charts/hapi-fhir-jpaserver/ci/extra-volumes-values.yaml, charts/hapi-fhir-jpaserver/templates/deployment.yaml, charts/hapi-fhir-jpaserver/templates/tests/test-endpoints.yaml, charts/hapi-fhir-jpaserver/values.yaml
```yaml
- kind: changed
description: "updated postgresql sub-chart to 16.3.2"
- kind: changed
description: "updated curlimages/curl to 8.11.1"
- kind: changed
description: "updated hapiproject/hapi to 7.6.0"
- kind: added
description: "support for setting resource limits and requests from presets. With a default set for all containers"
- kind: added
description: "support for setting extra volumes and volume mounts"
- kind: changed
description: "set default pod security context for main and test pods"
```
Closes #757
=> Helm chart dependency updates and support for extraVolumes and -Mounts

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml, src/main/resources/cds.application.yaml
This is a change to expose the following properties, from JpaStorageSettings, via configuration:
private boolean myPreExpandValueSets; // pre_expand_value_sets
private int myPreExpandValueSetsDefaultCount; // pre_expand_value_sets_default_count
private int myPreExpandValueSetsMaxCount; // pre_expand_value_sets_max_count
private boolean myEnableTaskPreExpandValueSets; // enable_task_pre_expand_value_sets
private int myMaximumExpansionSize; // maximum_expansion_size
=> Expose expansion properties as configuration

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml
Allows :
- to parametrize the polling interval of subscription
- to enable the setting to queue the subscription jobs immediately.
Following the change in #hapifhir/hapi-fhir/pull/6395
=> Externalizes more subscription parameters

pom.xml
This adds a revision number to the maven version for this project.
All releases from this point forward will be defined as a tagged commit in the master branch with a corresponding push of the project Docker images to DockerHub.
Each version of jpaserver-starter will be based on the HAPI release version it is based on, with a revision number.
**Format:**
`{HAPI-VERSION}-{REVISION-NUMBER}`
**Example:**
`8.0.0-1`
The revision number will increment when a new jpaserver-starter is released using the same HAPI version as its base.  Thus a sequence of releases based starting with HAPI 8.0.0 would look as follows:
* 8.0.0-1 (first release using HAPI 8.0.0)
* 8.0.0-2 (bug fix in jpaserver-starter)
* 8.0.0-3 (new config options provided in jpaserver-starter)
* 8.2.0-1 (first release using HAPI …
=> Revision Number Versioning

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/cds.application.yaml
Fixes the following issues:
* The "enable_task_pre_expand-value_setss" configuration option is misspelled and is corrected in this PR to: "setEnable_task_pre_expand_value_sets".
* The logging statements for the following expansion configuration options were incorrectly reporting the value of "pre_expand_value_sets_default_count" rather than their own corresponding value:
* "pre_expand_value_sets_max_count"
* "maximum_expansion_size"
=> Fixed expansion configuration options bugs

src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java
Because of the way the setters in JpaStorageSettings are defined for PreExpandValueSetsMaxCount and PreExpandValueSetsDefaultCount, if PreExpandValueSetsDefaultCount is set before PreExpandValueSetsMaxCount, PreExpandValueSetsDefaultCount will be reset to its default value by the setter for PreExpandValueSetsMaxCount.
This does not do anything to change the setters, but switches the order in which they are called from FhirServerConfigCommon.
=> Fixed bug in setting of jpaStorageSettings pre-expansion settings

src/main/resources/application.yaml
This pull request includes a configuration update to the `application.yaml` file, enhancing the server settings for better URL handling.
* Added a `tomcat` configuration block under `server` to allow the `|` character as a separator in URLs by setting `relaxed-query-chars`. This improves the flexibility of query parameters in the application.
=> feat: add support for relaxed query characters in Tomcat configuration

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/resources/application.yaml
This PR updates the `hapi-fhir-jpaserver-starter` to set `request_tenant_partitioning_mode = true` by default in AppProperties & `application.yaml`.  
This change ensures that multi-tenancy is enabled using the tenant ID in the request URL base, which is handled by the following logic:
```java
if (myAppProperties.getPartitioning().getRequest_tenant_partitioning_mode() == Boolean.TRUE) {
ourLog.info("Partitioning mode enabled in: Request tenant partitioning mode");
myRestfulServer.registerInterceptor(new RequestTenantPartitionInterceptor());
myRestfulServer.setTenantIdentificationStrategy(new UrlBaseTenantIdentificationStrategy());
}
=> fix: set default value for request_tenant_partitioning_mode to true to support easy default partitioning

src/main/java/ca/uhn/fhir/jpa/starter/util/EnvironmentHelper.java
see : https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/804
Summary: 
This PR is intended to address an issue where properties "spring.jpa.properties.*" are not being picked up when set as environment variables using Springboot's relaxed binding rules for environment variables (i.e. SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT). 
The docker-compose.yml file in the project currently doesn't work. (Not sure what changed and why it stopped working). 
In debugging that, I attempted to set the SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT as an env var in the docker-compose.yml file to fix it, and then discovered that the dialect was not being picked up. Hence this PR.
=> process jpa properties set as env variables

src/test/smoketest/plain_server.http
This pull request introduces a timeout (120s) configuration for the `validate` operation in the `plain_server.http` smoke test file. 
* [`src/test/smoketest/plain_server.http`](diffhunk://#diff-c0cf111e04ed2f38469fb078a0fda5521c8d908794adb999ed3d6b1db0c1a5a4R209): Added a `@timeout` directive to specify a maximum wait time of 2 minutes for the `$validate` operation response.
=> feat: add timeout comment for validate operation in plain_server.http

README.md
Documents sharp edge re: interceptor registration (https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/641).
=> docs: document interceptor registration for non-REST calls

src/main/java/ca/uhn/fhir/jpa/starter/AppProperties.java, src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java, src/main/resources/application.yaml, src/main/resources/cds.application.yaml, src/test/java/ca/uhn/fhir/jpa/starter/ElasticsearchLastNR4IT.java, src/test/resources/application.yaml
Add support to enable search index full text disabled by default https://github.com/hapifhir/hapi-fhir/pull/6426. This was enabled by default and non configurable for version 7.6.0 and older and disabled by default from version 8.0.0 and newer which can be enabled
Fixes: #807
=> feat: add support to enable search index full text
